### ISSUE TITLE
Payload [FIX]

### ISSUE THREAD

**Issue by Inzilkin** [crinny/vkcoin#6]
Короче, пейлоад в данный момент равняется tx, который можно узнать после оплаты. На самом же деле пейлоад должен быть кодом при оплате, что в данный момент не так. Прошу принять меры и починить пейлоад

**Comment by crinny** [comment]
Буду рад принять ваш Pull Request!

**Comment by Inzilkin** [comment]
К сожалению, я не буду делать pull request, чините сами!

**Comment by SpootiFM** [comment]
К сожалению, мы тоже не можем встать с дивана

**Comment by Inzilkin** [comment]
Тогда закрывайте вашу библиотеку, спасибо!

**Comment by crinny** [comment]
@SpootiFM Всмысле мы? В библиотеке же написано crinny

**Comment by SpootiFM** [comment]
Пожалуйста, пишите ещё

**Comment by Inzilkin** [comment]
@SpootiFM, @crinny, прошу закрыть библиотеку, либо же починить Payload!

**Comment by crinny** [comment]
- [ ] Починить пэйлоад
- [x] Закрыть библиотеку

**Comment by Inzilkin** [comment]
@crinny, Вы не удалили библиотеку, жду удаления.

**Comment by SpootiFM** [comment]
@Inzilkin прошу Себастьяна

**Comment by crinny** [comment]
Исправлено в 2.0
