### ISSUE TITLE
run_longpoll error

### ISSUE THREAD

**Issue by gsrozh** [crinny/vkcoin#7]
При запуске run_longpoll() ошибка self.longpoll_transaction = self.get_transactions(tx)['response']
Потому что ответ от get_transactions() возвращается без ['response'], а сразу в виде списка ([{'id': ***, 'from_id': ***, 'to_id': ***, 'amount': '100000', 'type': 3, 'payload': 0, 'external_id': ***, 'created_at': ***}])

**Comment by crinny** [comment]
[Исправлено](https://github.com/crinny/vkcoin/commit/c16e715ab03bb4c1761166ede938b69b112069cb) в версии 2.0.1
